### ISSUE TITLE
ProtocolLib??

### ISSUE THREAD

**Issue by max1mde** [corentingosselin/ProdigyCape#6]
First of all..
Really cool plugin & idea

But why make it so complicated by using ProtocolLib and NMS?
Its harder and takes more time to update such a project.

Please switch to Packet Events:
https://github.com/retrooper/packetevents

And Entity Lib:
https://github.com/Tofaa2/EntityLib

**Why these two libraries?**
Because you don't have to think about version depending stuff _(You only have to update the libraries when a new MC version comes out, not the source code in most cases)_ also with these libraries combined,
its as easy to work with packets as with the normal bukkit api.

If you do so, I will probably contribute to this project too!
If not I could maybe create a pull request for the changes...

# Some other stuff

(Wrong it's 1.19.4)
![image](https://github.com/corentingosselin/ProdigyCape/assets/114857048/4dac4ad1-6288-438e-91dc-028a6af2ca00)

# Ideas

I've also got some additional feature ideas:
- Modular cape (A cape which is built of multiple displays)
- A Java API (If it does not exist yet)

**Comment by corentingosselin** [comment]
Hello !

Thank you for the feedback 👍  I appreciate fresh ideas and tools

Unfortunately we must use nms and packet to do that, when I first started the plugin I used bukkit display entities. The plugin was working fine with that. And after more test, I found a big issue. You cannot teleport a player with a passenger. This is so crazy in minecraft code that the only way to fix that is by using packet. This means that you literally break all server with teleport plugin features.

You read in my mind, I wanted to use a lib like you just mentioned, but most of them was outdated or not working properly. And honestly I did not know this one. So yes let's remove protocollib !

However, not sure about entitylib. The cape transformation system is a bit tricky depending the version so I should keep native nms usage

You're right for 1.19.4, I was dizzy between minecarft version and nms R4 

I had a similar idea: 
- Modular cape (A cape which is built of multiple displays) <- But would be really complex to make because you need to have successive passengers
- My other idea, this one is not so difficult: an animated cape with different texture frames
- Or multiple cosmetics around the player hats, ears, ect

Java api of course, but I'm too lazy to do that xD

**Comment by max1mde** [comment]
Okay so...
You are right with the teleportation... I've had this issue too with my chat bubbles plugin (https://www.spigotmc.org/resources/115811/)

But with packet events & entity lib it does work because its also a packet lib like protocollib just in better and actively maintained.

Also I already wrote a plugin like a year ago for hat cosmetics using item displays (Not packet based) with serverside calculated rotation:
![image](https://github.com/corentingosselin/ProdigyCape/assets/114857048/32dc8ca8-f860-46ee-8d00-dd15d7ae8e17)
So its defenetly possible to add different types of cosmetics...

I can prob. implement the java api.

**Comment by corentingosselin** [comment]
Nice I will start the migration to packet events lib. I will try another migration with entity lib but I need to make sure that it does not break the current cape system.

Yes nice screenshot, this kind of idea should be another plugin with giant market place around every server. I bet someone  is already starting this kind of project. This could be a massive business

**Comment by max1mde** [comment]
Okay nice!

And yes this is a really wanted plugin... I also wanted to publish mine

**Comment by max1mde** [comment]
Like there are many people who want such cosmetics like hats, capes wings... for their server without a resourcepack

**Comment by corentingosselin** [comment]
> Okay nice!
> 
> And yes this is a really wanted plugin... I also wanted to publish mine

don't wait ! I will close this ticket, if you want to discuss more about the projects ect you can add me on discord: cocoraid
